# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2

  - name: Execute tests
    uses: joonvena/robotframework-docker-action@v0.1
    env:
      BROWSER: chrome
      ROBOT_TESTS_DIR: ${{ github.workspace }}/robot_tests
      ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports

  - name: Upload test results
    uses: actions/upload-artifact@v1
    if: always()
    with:
      name: reports
      path: ${{ github.workspace }}/reports
